#!/bin/sh

if [ $# -ne 3 ]
then
    echo "Usage: $0 NODE_ID IHEX DEST_DIR"
    echo "Example: $0 12 main.ihex user@host:/var/wisenet/nodes/telosb_XYZ/imgs/"
    echo "Note that DEST_DIR must be a directory!"
    exit 1
fi

NODE_ID=$1
IHEX_SRC=$2
IHEX_TMP=`mktemp -t ihex.XXXXXX`
DEST=$3

PATH=$PATH:/opt/msp430/bin/:/Users/core/wisenet/vendetta/bin

# tos-set-symbols --objcopy msp430-objcopy --objdump msp430-objdump --target ihex build/telosb/main.ihex build/telosb/main.ihex.out-255 TOS_NODE_ID=255 ActiveMessageAddressC$addr=255

tos-set-symbols --objcopy msp430-objcopy --objdump msp430-objdump --target ihex \
          $IHEX_SRC $IHEX_TMP \
		  $NODE_ID
#          TOS_NODE_ID=$NODE_ID ActiveMessageAddressC\$addr=$NODE_ID

if [ $? -ne 0 ]
then
    rm $IHEX_TMP
    echo "Setting symbols failed!"
    exit 2
fi

scp $IHEX_TMP $DEST/`basename $IHEX_SRC`

rm $IHEX_TMP

exit $?

# tos-bsl --telosb -c /dev/ttyUSB0 -r -e -I -p /opt/moteiv/tos/lib/Deluge/TOSBoot/build/tmoteinvent/main.ihex
# tos-bsl --telosb -c /dev/ttyUSB0 -r -I -p build/tmoteinvent/main.ihex.out-3
